### ISSUE TITLE
Add ability to pass the Netlify CLI version

### ISSUE THREAD

**Issue by what1s1ove** [South-Paw/action-netlify-cli#5]
Hey! Thanks for creating such an awesome action!

I wanted to bring up an issue regarding the Netlify CLI. After the release of v17.36.2, it started having some problems ([see details](https://github.com/netlify/cli/issues/6841)). The only current workaround is to downgrade the CLI to v17.36.1. Unfortunately, this means that anyone using this action for deployments is blocked until the Netlify team fixes the issue in future versions 🥲

**Comment by South-Paw** [comment]
I've also hit the same issue within a monorepo with the Netlify CLI.

I just checked out the workflows for that project as I recalled doing something to work around the issue... and it looks like I've pinned v15 explicitly in a `npx command`

```
- name: Deploy to Netlify
  run: npx --yes netlify-cli@15.11.0 deploy --json --prod --dir=apps/user/dist
  env:
    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
```

The downside being the command output is not being parsed nor made available by the step for other steps...

Adding a way to specify the cli package version would certainly be useful though 👍
